name: Meralda Call Automation

on:
  push:
    branches: [AddingGithubActions]
  pull_request:
    branches: [AddingGithubActions]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Run Android emulator and tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
       api-level: 33
       target: google_apis
       arch: x86                
       emulator-options: -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect
       disable-animations: true
       force-avd-creation: true
       avd-name: test
       script: |
        mvn clean install -DskipTests
        chmod +x run_both.sh
        ./run_both.sh
